name: ci

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js v14.x
      uses: actions/setup-node@v1
      with:
        node-version: v14.x
    - run: make install
    - run: make test-quiet
    - run: make lint
